---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restarting networkd service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: systemd-networkd
...
