---    
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restarting networking service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: networking

- name: Restarting pihole-pod service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: pihole-pod

...
