---
- name: Get current version codename
  ansible.builtin.shell: . /etc/os-release; echo $VERSION_CODENAME
  register: codename

- name: Upgrade to testing (sources.list)
  ansible.builtin.shell: sed -i 's/{{ codename.stdout }}/testing/g' /etc/apt/sources.list
  when: codename.stdout != "trixie"

- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
    purge: true
    name: "*"
    state: latest

- name: Check if a reboot is needed for Debian
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_checksum=no

- name: Reboot the Debian
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
...
