---
- name: bare_metal
  hosts: bare_metal
  become: true
  gather_facts: true

  roles:
    #- role: debian-update
    - role: bare-metal

- name: firewall
  hosts: lxc_firewall
  become: true
  gather_facts: true

- name: kube
  hosts: lxc_kube
  become: true
  gather_facts: true
...

