---
- name: bare_metal
  hosts: bare_metal
  become: true
  gather_facts: true

  roles:
    - role: debian-update
    - role: bare-metal
    #- role: lx-nas

- name: kube
  hosts: lx_kube
  become: true
  gather_facts: true
...

