---
- name: Installing dependencies
  ansible.builtin.apt:
    pkg: "{{ dotfiles.dependencies }}"
    update_cache: no

- name: Deleting .bashrc
  ansible.builtin.file:
    path: "/home/{{ dotfiles.user.login }}/.bashrc"
    state: absent

- name: Deleting .bash_logout
  ansible.builtin.file:
    path: "/home/{{ dotfiles.user.login }}/.bash_logout"
    state: absent

- name: Deleting .profile
  ansible.builtin.file:
    path: "/home/{{ dotfiles.user.login }}/.profile"
    state: absent
  become: yes
  become_user: "{{ dotfiles.user.login }}"

- name: Generate SSH key
  ansible.builtin.user:
    name: "{{ dotfiles.user.login }}"
    shell: /usr/bin/zsh
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    ssh_key_passphrase: ""
    force: no

- name: Copy ssh config
  ansible.builtin.template:
    src: home/.ssh/config.j2
    dest: "/home/{{ dotfiles.user.login }}/.ssh/"

- name: Cloning dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles.repo.url }}"
    dest: "/home/{{ dotfiles.user.login }}/.dotfiles"
    clone: yes
    update: yes
  become: yes
  become_user: "{{ dotfiles.user.login }}"

- name: Installing configs
  ansible.builtin.command:
    cmd: "stow {{ item }}"
    chdir: "/home/{{ dotfiles.user.login }}/.dotfiles"
  with_items:
    "{{ dotfiles.configs }}"
  become: yes
  become_user: "{{ dotfiles.user.login }}"
...