---
- name: Init podman
  import_tasks: podman.yml

- name: Creates directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /root/services-pod/
    - /media/data/pihole/etc-pihole
    - /media/data/pihole/etc-dnsmasq.d

- name: Copy pod definition
  ansible.builtin.template:
    src: root/services-pod/pihole-pod.yml.j2
    dest: /root/services-pod/pihole-pod.yml
  register: kube_definition_changed

- name: Copy systemd pod definition
  ansible.builtin.copy:
    src: etc/containers/systemd/pihole.kube
    dest: /etc/containers/systemd/pihole-pod.kube
  register: kube_definition_changed

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: kube_definition_changed

- name: Restarting pihole-pod service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: pihole-pod
  when: kube_definition_changed

- name: Get stats before of adlists.list
  ansible.builtin.stat:
    path: /media/data/pihole/etc-pihole/adlists.list
    get_checksum: yes
  register: adlist_before

- name: get service facts
  ansible.builtin.service_facts:

- name: "Import adlists with bash"
  loop_control:
    loop_var: adlist
  ansible.builtin.command: "podman exec pihole-pod-pihole /bin/sh -c '/usr/local/bin/pihole -a adlist add {{ adlist }}'"
  loop: "{{ pihole.adlist}}"
  when: ( ansible_facts.services["pihole-pod.service"] is defined and ansible_facts.services["pihole-pod.service"].state == "running" )
    
- name: Get stats after of adlists.list
  ansible.builtin.stat:
    path: /media/data/pihole/etc-pihole/adlists.list
    get_checksum: yes
  register: adlist_after

- name: "Restarting pihole-pod-pihole gravity"
  ansible.builtin.command: "podman exec pihole-pod-pihole /bin/sh -c '/usr/local/bin/pihole -g'"
  when: ( ( ansible_facts.services["pihole-pod.service"] is defined and ansible_facts.services["pihole-pod.service"].state == "running" ) and ( not adlist_before.stat.exists or adlist_after.stat.checksum != adlist_before.stat.checksum ) )
...