---
- name: Get network tools
  ansible.builtin.apt:
    pkg:
      - iptables
    update_cache: no

- name: Wan up script
  ansible.builtin.copy:
    src: etc/network/if-up.d/ns-wan.sh
    dest: /etc/network/if-up.d/ns-wan.sh
    mode: '0755'
  notify:
    - Restarting networking service
   
- name: Wan down script
  ansible.builtin.copy:
    src: etc/network/if-down.d/ns-wan.sh
    dest: /etc/network/if-down.d/ns-wan.sh
    mode: '0755'
  notify:
    - Restarting networking service
...