---
- name: Creates directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /root/services-pod/
    - /media/data/pihole/etc-pihole
    - /media/data/pihole/etc-dnsmasq.d
    - /run/systemd/generator/default.target.wants

- name: Copy pod definition
  ansible.builtin.template:
    src: root/services-pod/pihole-pod.yml.j2
    dest: /root/services-pod/pihole-pod.yml      
  notify:
    - Restarting pihole-pod service

- name: Copy systemd pod definition
  ansible.builtin.copy:
    src: etc/containers/systemd/pihole.kube
    dest: /etc/containers/systemd/pihole-pod.kube      
  notify:
    - Reload systemd

- name: Create a symbolic link
  ansible.builtin.file:
    src: /run/systemd/generator/pihole-pod.service
    dest: /run/systemd/generator/default.target.wants/pihole-pod.service
    state: link
    force: true
  notify:
    - Reload systemd
    - Restarting pihole-pod service

- name: Get stats before of adlists.list
  ansible.builtin.stat:
    path: /media/data/pihole/etc-pihole/adlists.list
    get_checksum: yes
  register: adlist_before

- name: get service facts
  ansible.builtin.service_facts:

- name: "Import adlists with bash"
  loop_control:
    loop_var: adlist
  ansible.builtin.command: "podman exec pihole-pod-pihole /bin/sh -c '/usr/local/bin/pihole -a adlist add {{ adlist }}'"
  loop: "{{ pihole.adlist}}"
  when: ( ansible_facts.services["pihole-pod.service"] is defined and ansible_facts.services["pihole-pod.service"].state == "running" ) 
    
- name: Get stats after of adlists.list
  ansible.builtin.stat:
    path: /media/data/pihole/etc-pihole/adlists.list
    get_checksum: yes
  register: adlist_after

- name: "Restarting pihole-pod-pihole gravity"
  ansible.builtin.command: "podman exec pihole-pod-pihole /bin/sh -c '/usr/local/bin/pihole -g'"
  when: ( ( ansible_facts.services["pihole-pod.service"] is defined and ansible_facts.services["pihole-pod.service"].state == "running" ) and ( not adlist_before.stat.exists or adlist_after.stat.checksum != adlist_before.stat.checksum ) )
...