---
- name: Update repositories cache and install podman packages
  ansible.builtin.apt:
    pkg:
      - podman
    update_cache: no

- name: Configuring registries
  ansible.builtin.copy:
    dest: /etc/containers/registries.conf
    content: |
      unqualified-search-registries=["docker.io", "quay.io"]
...