---
- name: Disable networking service
  ansible.builtin.systemd_service:
    enabled: false
    daemon_reload: true
    name: networking
     
- name: Enable networkd service
  ansible.builtin.systemd_service:
    enabled: true
    daemon_reload: true
    name: systemd-networkd
...