---
- name: Copy systemd lan network definition
  ansible.builtin.copy:
    src: etc/systemd/network/10-lanbr0.netdev
    dest: /etc/systemd/network/
    mode: '0644'
  notify:
    - Restarting networkd service

- name: Copy systemd lan network definition
  ansible.builtin.copy:
    src: etc/systemd/network/11-lanbr0-nic.network
    dest: /etc/systemd/network/
    mode: '0644'
  notify:
    - Restarting networkd service

- name: Copy systemd lan network definition
  ansible.builtin.copy:
    src: etc/systemd/network/12-lan.network
    dest: /etc/systemd/network/
    mode: '0644'
  notify:
    - Restarting networkd service
...